allowBuilds:
  better-sqlite3: set this to true or false
  esbuild: set this to true or false
  lefthook: set this to true or false
  msw: set this to true or false
  sharp: set this to true or false
onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - lefthook
  - msw
  - sharp
